# SPDX-FileCopyrightText: © 2024 David Bliss
#
# SPDX-License-Identifier: GPL-3.0-or-later

[package]
name = "fotema"
version = "1.3.0"
authors = ["David Bliss <hello@fotema.app>"]
edition = "2021"
publish = false

[workspace]
members = ["core"]

[profile.release]
lto = true
codegen-units = 1

[dependencies]
gettext-rs = { version = "0.7", features = ["gettext-system"] }
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.18", features = ["chrono", "env-filter"] }
relm4 = { version = "0.8.1", features = ["libadwaita", "gnome_46"] }
itertools = "0.12.1"
humansize = "2.1.3"
rayon = "1.10.0"
glycin = "1.0.2"
futures = "0.3.30"
chrono = "0.4.38"
anyhow = "1.0.83"
strum = { version = "0.26.2", features = ["derive"] }


[dependencies.fotema_core]
path = "core"
