# SPDX-FileCopyrightText: © 2024 David Bliss
#
# SPDX-License-Identifier: GPL-3.0-or-later

# https://taskfile.dev

version: '3'

vars:
  COPYRIGHT: "David Bliss"
  YEAR:
    sh: "date +%Y"

tasks:

  install-fedora-deps:
    desc: Install development libraries
    cmds:
      - sudo dnf install -y libavformat-free-devel
      - sudo dnf install -y libavfilter-free-devel
      - sudo dnf install -y libavdevice-free-devel
      - sudo dnf install -y clang-libs
      - sudo dnf install -y clang-devel
      - sudo dnf install -y libadwaita-devel

  flatpak-devel:
    desc: Development build and install with flatpak-builder
    cmds: 
      - flatpak-builder --user --install --force-clean flatpak_app build-aux/dev.romantics.Fotema.Devel.json

  flatpak-release:
    desc: Release build and install with flatpak-builder
    cmds:
      - flatpak-builder --user --install --force-clean flatpak_app build-aux/dev.romantics.Fotema.json

  licence-update:
    desc: "Update licence annotations for project files"
    cmds:
      - reuse annotate 
        --recursive 
        --skip-existing
        --fallback-dot-license 
        --copyright "{{ .COPYRIGHT }}" 
        --license "GPL-3.0-or-later"
        --year {{ .YEAR }} 
        --copyright-style spdx-symbol 
        .

  licence-lint:
    desc: "Lint licences"
    cmds:
      - reuse lint
