# SPDX-FileCopyrightText: © 2024 David Bliss
#
# SPDX-License-Identifier: GPL-3.0-or-later

[package]
name = "photos_core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.37"
image = "0.25.0"
kamadak-exif = "0.5.5"
rayon = "1.10.0"
rusqlite = { version = "0.31.0", features = ["bundled", "chrono"] }
walkdir = "2.5.0"

[dev-dependencies]
tempfile = "3.10.1"

